use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - bing
      - google

server:
  secret_key: "${SEARXNG_SECRET_KEY}"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  formats:
    - html
    - json
